In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [5]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of list_:", type(list_[0]))
print("Data tyoe of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data tyoe of array_list: <U1


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [1]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
print("Data type of element in list_:")
for element in list_:
    print(type(element))
print("Data type of element in list")
for element in array_list:
    print(type(element))


Data type of element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of element in list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [3]:
array_list = np.array(object=list_, dtype= int)
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)
print("Data type of element in list_:")
for element in list_:
    print(type(element))
print("Data type of element in list")
for element in array_list:
    print(type(element))



Data type of element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of element in list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [4]:
import numpy as np
num_list = [[1,2,3], [4,5,6]]
num_array = np.array(object=num_list)
#(i) Shape
print("sum of num_array:", num_array.shape)
#(ii) size
print("sum of num_array:", num_array.size)

sum of num_array: (2, 3)
sum of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [8]:
import numpy as np
Zeros_array = np.zeros((3,3))
print(Zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0]

In [9]:
import numpy as np
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
